### ISSUE TITLE
module initialization error: 'db_user'

### ISSUE THREAD

**Issue by t-readyroc** [awslabs/amazon-redshift-monitoring#4]
I'm getting the error in the subject each time the function is invoked.  Is there a way for me to better diagnose the issue?  The function logs in CloudWatch aren't very verbose besides to point out the module error.

**Comment by pvbouwel** [comment]
Do you have any additional information on how you arrive at this error?  Generally module initialization errors mean that Lambda cannot start the function due to an error in the code.  That being said in my experience it gives descriptive errors like: `Syntax error in module 'lambda_function': invalid syntax (lambda_function.py, line 20)` or `module initialization error: name 'db_user' is not defined`

Did you perform any changes to the provided code?  Have you tried deploying it as is and using the environment variables?

**Comment by t-readyroc** [comment]
Thanks for the reply - I'm not sure where else to get any further info.  [Here](http://i.imgur.com/38GEZ2s.png) is a screenshot of the relevant CloudWatch log entries, expanded.  I have changed the information in the code; I've filled out my own values for:

- user
- enc_password
- host
- port
- database
- cluster 

Is there not another location I should be searching for more descriptive error msgs?

**Comment by javierros** [comment]
I've updated the source code, there were a bug when you modified the values of the parameters in the source code instead of use the Lambda parameters. In any case I'd recommend you the usage of the Lambda parameters instead of writing the values in the lambda function code.
